name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: nodejs-alptech-project
  GAR_LOCATION: us-central1
  CLUSTER_NAME: alptech-cluster
  CLUSTER_REGION: us-central1
  IMAGE_NAME: nodejs-alptech-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Configure Docker to use Artifact Registry
      run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/nodejs-app-repo/$IMAGE_NAME:stable .
        docker push $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/nodejs-app-repo/$IMAGE_NAME:stable

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.CLUSTER_NAME }}
        location: ${{ env.CLUSTER_REGION }}

    - name: Deploy via Helm
      run: |
        helm upgrade --install nodejs-app ./helm/nodejs-app \
          --namespace default \
          --set image.repository=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/nodejs-app-repo/$IMAGE_NAME \
          --set image.tag=stable
